# Generated by Django 2.2.6 on 2019-11-21 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_pass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=50)),
                ('system_name', models.CharField(max_length=30)),
                ('user_comment', models.TextField(blank=True)),
                ('page_url', models.URLField(blank=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submitbox.AppUser')),
            ],
        ),
    ]
